-- CreateTable
CREATE TABLE "pokemon" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "name" TEXT NOT NULL,
    "pokedex_number" INTEGER NOT NULL,
    "abilities" TEXT NOT NULL,
    "typing" TEXT NOT NULL,
    "hp" INTEGER NOT NULL,
    "attack" INTEGER NOT NULL,
    "defense" INTEGER NOT NULL,
    "special_attack" INTEGER NOT NULL,
    "special_defense" INTEGER NOT NULL,
    "speed" INTEGER NOT NULL,
    "height" INTEGER NOT NULL,
    "weight" INTEGER NOT NULL,
    "genus" TEXT NOT NULL,
    "gen_introduced" INTEGER NOT NULL,
    "female_rate" REAL NOT NULL,
    "genderless" INTEGER NOT NULL,
    "baby_pokemon" INTEGER NOT NULL,
    "legendary" INTEGER NOT NULL,
    "mythical" INTEGER NOT NULL,
    "is_default" INTEGER NOT NULL,
    "forms_switchable" INTEGER NOT NULL,
    "base_experience" INTEGER NOT NULL,
    "capture_rate" INTEGER NOT NULL,
    "egg_groups" TEXT NOT NULL,
    "egg_cycles" REAL NOT NULL,
    "base_happiness" INTEGER NOT NULL,
    "can_evolve" INTEGER,
    "evolves_from" TEXT NOT NULL,
    "primary_color" TEXT NOT NULL,
    "shape" TEXT NOT NULL,
    "number_pokemon_with_typing" REAL NOT NULL,
    "normal_attack_effectiveness" REAL NOT NULL,
    "fire_attack_effectiveness" REAL NOT NULL,
    "water_attack_effectiveness" REAL NOT NULL,
    "electric_attack_effectiveness" REAL NOT NULL,
    "grass_attack_effectiveness" REAL NOT NULL,
    "ice_attack_effectiveness" REAL NOT NULL,
    "fighting_attack_effectiveness" REAL NOT NULL,
    "poison_attack_effectiveness" REAL NOT NULL,
    "ground_attack_effectiveness" REAL NOT NULL,
    "fly_attack_effectiveness" REAL NOT NULL,
    "psychic_attack_effectiveness" REAL NOT NULL,
    "bug_attack_effectiveness" REAL NOT NULL,
    "rock_attack_effectiveness" REAL NOT NULL,
    "ghost_attack_effectiveness" REAL NOT NULL,
    "dragon_attack_effectiveness" REAL NOT NULL,
    "dark_attack_effectiveness" REAL NOT NULL,
    "steel_attack_effectiveness" REAL NOT NULL,
    "fairy_attack_effectiveness" REAL NOT NULL
);

-- CreateTable
CREATE TABLE "pokemon_status" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "pokemon_id" INTEGER NOT NULL,
    "status" TEXT NOT NULL
);

